### ISSUE TITLE
Adds parenthesis on start of `form_for` but not corrosponding `end`

### ISSUE THREAD

**Issue by atavistock** [feliperenan/heex_formatter#30]
For example:
```
<%= form_for @changeset, Routes.sign_in_path(@conn, :create), fn f -> %>
  // 30 lines of html
<% end %>
```

gets turned into 
```
<%= form_for(@changeset, Routes.sign_in_path(@conn, :create), fn f -> %>
  // 30 lines of html
<% end %>
```

**Comment by atavistock** [comment]
Before format:
```
<%= form_for @changeset, Routes.sign_in_path(@conn, :create), fn f -> %>
  <%= email_input f, :email_address %>
<% end %>
```

After format:
```
<%= form_for(@changeset, Routes.sign_in_path(@conn, :create), fn f -> %>
  <%= email_input(f, :email_address) %>
<% end %>
```

Most notable is that the `form` acquires a parenthesis, but the `end` for the function does not

**Comment by jsmestad** [comment]
Glad to see this was already reported. Hit this myself

**Comment by feliperenan** [comment]
Yes, I have been thinking how we could solve this. Just for you guys to understand what going on here. 

It adds parentheses only in the beginning because that is formatted by the official mix format that formats our regular Elixir code. And, because this `form` takes a function as last argument (not a block) the parentheses is added.

We might need to handle this case ourselves after Elixir format adds these parentheses. But a temp solution, in case you don't want to have parentheses at all is tweaking your `.formatter.exs` like this:

```elixir
[
  # ...
  locals_without_parens: [form_for: 3, form_for: 4],
]
```

**Comment by jsmestad** [comment]
@feliperenan Worth adding `inputs_for: 3` and `inputs_for: 4` to that list as well

**Comment by atavistock** [comment]
Another work around is to use the `.form` helper recently introduced.

**Comment by josevalim** [comment]
Master version no longer formats code inside eex do-end blocks, as there are many issues, so this issue no longer exists!
