### ISSUE TITLE
`label` function not processed  

### ISSUE THREAD

**Issue by atavistock** [feliperenan/heex_formatter#32]
After running the formatter converts `inputs`

```
<%= email_input f, :email_address size: 40 %>
```

becomes

```
<%= email_input(f, :email_address,
    size: 40
) %>
```

but these labels are untouched
```
<%= label f, :email_address, class: "text-gray font-medium" do %>
  Email Address
<% end %>
```

**Comment by feliperenan** [comment]
Hi @atavistock. Thank you for reporting this :)

I got a different output trying to format this label and found another issue with that. This PR aims to fix that: https://github.com/feliperenan/heex_formatter/pull/35

Regarding the parentheses in this label, I don't know if they should have it because in this case it is a block and it follows the same rule it would for `ifs/fors/cases` which comes directly from Elixir format.

Maybe @paulo-silva has some thoughts here?

**Comment by paulo-silva** [comment]
yeah, we use `Code.format_string/2` to format eex; I thought that this could be related to `locals_without_parens`, but it's odd that in email_input, it adds parentheses and in label not 🤔

**Comment by atavistock** [comment]
In the scheme of things this is not really a big deal, just inconsistent

**Comment by 03juan** [comment]
For what it's worth I'm seeing this with old-style `live_component` calls on master.

```html
<%= live_component :function %>
```

becomes

```html
<%= live_component(:function) %>
```

**Comment by feliperenan** [comment]
Unfortunately there is nothing we can do here as this label version is being handled as block and, parentheses are not added in this case.

You might want to add email_input to your list of local_without_params in order to make it all consistent ;)
