### ISSUE TITLE
Failing to format consecutive embedded Elixir tags in a style tag

### ISSUE THREAD

**Issue by JohnDoneth** [feliperenan/heex_formatter#66]
Formatter commit used: [c1ffe57](https://github.com/feliperenan/heex_formatter/commit/c1ffe5741801793df5eea78dc042cca566bf91ed) 

I'm working with a couple of files which contain interpolated styles using HEEx and are failing to format. I was able to trim it down to this minimal reproduction: 
```html
<style>
  :root {
    <%= 2 + 2 %>
    <%= 2 + 2 %>
  }
</style>
```

```
❯ mix format
[
  {:tag_block, "style", [],
   [
     {:text, "\n  :root {\n    ", %{newlines: 1}},
     {:eex, "2 + 2", %{column: 5, line: 3, opt: '='}},
     {:text, "\n    ", %{newlines: 1}},
     {:eex, "2 + 2", %{column: 5, line: 4, opt: '='}},
     {:text, "\n  }\n", %{newlines: 1}}
   ]}
]
mix format failed for file:
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not a nonempty list

    :erlang.tl([])
    lib/heex_formatter/algebra.ex:258: HeexFormatter.Algebra.text_to_algebra/3
    lib/heex_formatter/algebra.ex:209: HeexFormatter.Algebra.to_algebra/2
    lib/heex_formatter/algebra.ex:42: anonymous fn/3 in HeexFormatter.Algebra.block_to_algebra/2
    (elixir 1.13.2) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/heex_formatter/algebra.ex:39: HeexFormatter.Algebra.block_to_algebra/2
    lib/heex_formatter/algebra.ex:119: HeexFormatter.Algebra.to_algebra/2
    lib/heex_formatter/algebra.ex:36: HeexFormatter.Algebra.block_to_algebra/2
```
It seems to get as far as the third node: `{:text, "\n    ", %{newlines: 1}}` before failing.

**Comment by feliperenan** [comment]
I guess I know what is going on here. The issue is that we trim new lines when processing style/script tag:

https://github.com/feliperenan/heex_formatter/blob/main/lib/heex_formatter/algebra.ex#L212

And, in this case, the indentation of the `eex` is in the previous node. We can't just just fix the match in `HeexFormatter.Algebra.text_to_algebra/3` but also make sure we are going to keep the User's format.

We should somehow check if the next node is an eex so we wouldn't trim the text 🤔
