### ISSUE TITLE
Formatter adds space around nested dynamic content, breaking :empty css pseudoclass

### ISSUE THREAD

**Issue by kerryb** [feliperenan/heex_formatter#69]
Another whitespace edge case I’m afraid (tested in 5fdff54) …

Starting with the the standard live layout created by `mix phx.new`:

```html
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>
```

Running the formatter inserts newlines:

```html
  <p class="alert alert-info" role="alert" phx-click="lv:clear-flash" phx-value-key="info">
    <%= live_flash(@flash, :info) %>
  </p>
```

This adds whitespace html nodes either side of the inner element, which means that even if there is no content in the flash, the css rule for `.alert:empty` doesn’t match, so empty flash divs appear on the page.

**Comment by 03juan** [comment]
Unfortunately treating white space-only child nodes as `:empty` is still a [level 4 css draft](https://drafts.csswg.org/selectors-4/#the-empty-pseudo), no browsers support it except Mozilla with non-standard `:-moz-only-whitespace`

**Comment by feliperenan** [comment]
That is similar to this issue here: https://github.com/feliperenan/heex_formatter/issues/16

I guess that  is an issue we have to live with because those spaces are required in order to proper format the code. These cases will need to be handled either by CSS or not rendering the content in case it is empty if possible.
